// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iPJk9cn3rkQGEeoULlu5D4mShvErek8',
    appId: '1:99724629910:web:19f23fd6b2288ad54fafb7',
    messagingSenderId: '99724629910',
    projectId: 'reddit-flutter-553b0',
    authDomain: 'reddit-flutter-553b0.firebaseapp.com',
    storageBucket: 'reddit-flutter-553b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcsrFTF9QNRFjYnr8EbHPDLIax0tHolg',
    appId: '1:99724629910:android:56aff3ac3327ff504fafb7',
    messagingSenderId: '99724629910',
    projectId: 'reddit-flutter-553b0',
    storageBucket: 'reddit-flutter-553b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFe7WEwnq1r69g74BXonQoy4yctZc9yoA',
    appId: '1:99724629910:ios:76f8693fb44e569d4fafb7',
    messagingSenderId: '99724629910',
    projectId: 'reddit-flutter-553b0',
    storageBucket: 'reddit-flutter-553b0.appspot.com',
    iosClientId: '99724629910-5jr02ba9aiosugt2iaua633igudv66fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
